#![allow(dead_code, unused_imports)]
use super::codeblock::{
    MermaidRenderMode, QuiverRenderMode, TikzRenderMode, render_mermaid,
    render_quiver, render_tikz,
};
use super::content::{NodeRenderConfig, render_content};
use super::latex::render_latex;
use super::utils;
use super::vault_db::VaultDB;
use crate::ast::{
    Node,
    NodeKind::{self, *},
    Tree,
};
use crate::export::utils::range_to_anchor_id;
use crate::export::vault_db::{
    FileLevelInfo, StaticVaultStore, VaultLevelInfo,
};
use crate::link::Referenceable;
use crate::link::scan_vault;
use insta::*;
use maud::DOCTYPE;
use maud::{Markup, PreEscaped, html};
use pulldown_cmark::{CodeBlockKind, LinkType};
use std::path::{Path, PathBuf};

use std::fs;

fn format_html_simple(html: &str) -> String {
    html.replace("><", ">\n<")
        .replace("<h", "\n<h")
        .replace("<p", "\n<p")
        .replace("</article>", "\n</article>")
}

fn prettify_html(html: &str) -> String {
    use std::io::Write;
    use std::process::{Command, Stdio};

    let mut child = Command::new("prettier")
        .arg("--parser")
        .arg("html")
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .spawn()
        .expect("prettier not found");

    child
        .stdin
        .as_mut()
        .unwrap()
        .write_all(html.as_bytes())
        .unwrap();
    let output = child.wait_with_output().unwrap();
    String::from_utf8(output.stdout).unwrap()
}

fn render_full_html(content: &str) -> String {
    html! {
        (DOCTYPE)
        body {
            (PreEscaped(content))
        }
    }
    .into_string()
}

fn render_single_page(note_vault_path: &Path) -> String {
    use tempfile::tempdir;
    let temp_dir = tempdir().unwrap();
    let temp_dir_path = temp_dir.path();

    // Copy note to temp dir
    let temp_note_path =
        temp_dir_path.join(note_vault_path.file_name().unwrap());
    fs::copy(note_vault_path, &temp_note_path).unwrap();

    let vault_db = StaticVaultStore::new_from_dir(temp_dir_path, false);
    let node_render_config = NodeRenderConfig::default();

    let md_src = fs::read_to_string(&temp_note_path).unwrap();
    let tree = Tree::new(&md_src);
    let markup = render_content(
        &tree,
        temp_dir_path,
        &vault_db,
        &node_render_config,
        0,
        1,
    );

    prettify_html(&markup.into_string())
}

#[test]
fn render_callout() {
    let path = std::path::PathBuf::from("tests/data/notes/callout.md");
    let out = render_single_page(&path);
    assert_snapshot!(out, @r#"
    <article>
      <blockquote><p>This is a note</p></blockquote>
      <callout data-callout="tip"
        ><callout-title
          ><callout-icon></callout-icon
          ><callout-title-text>Tip</callout-title-text></callout-title
        ><callout-content
          ><p>[!Tip] tip with one space</p></callout-content
        ></callout
      ><callout data-callout="tip"
        ><callout-title
          ><callout-icon></callout-icon
          ><callout-title-text>Tip</callout-title-text></callout-title
        ><callout-content
          ><p>[!Tip] tip with zero space</p></callout-content
        ></callout
      >
      <blockquote>
        <p>[!Tip] tip with 2 space -&gt; not a callout, just blockquote</p>
      </blockquote>
      <callout data-callout="tip"
        ><callout-title
          ><callout-icon></callout-icon
          ><callout-title-text>title</callout-title-text></callout-title
        ><callout-content
          ><p>[!Tip] title This is a tip with title</p></callout-content
        ></callout
      ><callout data-callout="tip"
        ><callout-title
          ><callout-icon></callout-icon
          ><callout-title-text>title</callout-title-text></callout-title
        ><callout-content><p>[!Tip] title</p></callout-content></callout
      >
      <blockquote><p>This is a separate block quote</p></blockquote>
      <callout data-callout="warning"
        ><callout-title
          ><callout-icon></callout-icon
          ><callout-title-text>Warning</callout-title-text></callout-title
        ><callout-content
          ><p>[!WARNING] This is a warning</p></callout-content
        ></callout
      ><callout data-callout="llm"
        ><callout-title
          ><callout-icon></callout-icon
          ><callout-title-text>LLM</callout-title-text></callout-title
        ><callout-content
          ><p>[!LLM] This is generated by LLM</p></callout-content
        ></callout
      ><callout data-callout="question"
        ><callout-title
          ><callout-icon></callout-icon
          ><callout-title-text
            >Can callouts be nested?</callout-title-text
          ></callout-title
        ><callout-content
          ><p>[!question] Can callouts be nested?</p>
          <callout data-callout="todo"
            ><callout-title
              ><callout-icon></callout-icon
              ><callout-title-text
                >Yes!, they can.</callout-title-text
              ></callout-title
            ><callout-content
              ><p>[!todo] Yes!, they can.</p>
              <callout data-callout="example"
                ><callout-title
                  ><callout-icon></callout-icon
                  ><callout-title-text
                    >You can even use multiple layers of
                    nesting.</callout-title-text
                  ></callout-title
                ><callout-content
                  ><p>
                    [!example] You can even use multiple layers of nesting.
                  </p></callout-content
                ></callout
              ></callout-content
            ></callout
          ></callout-content
        ></callout
      >
    </article>
    "#);
}
