#[cfg(test)]
mod tests {
    use crate::ast::Tree;
    use crate::link::Referenceable;
    use crate::link::build_links;

    use super::*;
    use crate::link::extract::scan_note;
    use insta::{assert_debug_snapshot, assert_snapshot};

    #[test]
    fn callout() {
        let md_src = r#"> [!NOTE]
> This is a note

> [!TIP]
> This is a tip

> [!WARNING]
> This is a warning"


> [!LLM]
> This is generated by LLM
"#;
        let tree = Tree::new(md_src);
        assert_snapshot!(&tree.root_node, @r#"
        Document [0..126]
          BlockQuote(Some(Note)) [0..27]
            Paragraph [12..27]
              Text(Borrowed("This is a note")) [12..26]
          BlockQuote(Some(Tip)) [28..53]
            Paragraph [39..53]
              Text(Borrowed("This is a tip")) [39..52]
          BlockQuote(Some(Warning)) [54..88]
            Paragraph [69..88]
              Text(Borrowed("This is a warning")) [69..86]
              Text(Inlined(InlineStr { inner: [226, 128, 156, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], len: 3 })) [86..87]
          BlockQuote(None) [90..126]
            Paragraph [92..126]
              Text(Borrowed("[")) [92..93]
              Text(Borrowed("!LLM")) [93..97]
              Text(Borrowed("]")) [97..98]
              SoftBreak [98..99]
              Text(Borrowed("This is generated by LLM")) [101..125]
        "#);
    }

    #[test]
    fn embed_image() {
        let path =
            std::path::PathBuf::from("tests/data/vaults/embed_image/note.md");
        let md_src = std::fs::read_to_string(&path).unwrap();
        let tree = Tree::new(&md_src);
        assert_snapshot!(&tree.root_node, @r#"
        Document [1..60]
          Paragraph [1..26]
            Text(Borrowed("Image")) [1..6]
            SoftBreak [6..7]
            Link { link_type: WikiLink { has_pothole: false }, dest_url: Borrowed("blue-image.png"), title: Borrowed(""), id: Borrowed("") } [7..24]
              Text(Borrowed("blue-image.png")) [9..23]
          Paragraph [28..60]
            Text(Borrowed("Embed Image")) [28..39]
            SoftBreak [39..40]
            Image { link_type: WikiLink { has_pothole: false }, dest_url: Borrowed("blue-image.png"), title: Borrowed(""), id: Borrowed("") } [40..58]
              Text(Borrowed("blue-image.png")) [43..57]
        "#);
    }

    #[test]
    fn frontmatter() {
        let path = std::path::PathBuf::from(
            "tests/data/vaults/frontmatter/article.md",
        );
        let md_src = std::fs::read_to_string(&path).unwrap();

        let tree = Tree::new(&md_src);
        assert_snapshot!(&tree.root_node, @r#"
        Document [0..243]
          MetadataBlock(YamlStyle) [0..135]
            Text(Borrowed("title: Getting Started\nauthor: Jane Doe\ndate: 2024-03-15\ntags:\n  - programming\n  - tutorial\ncategory: tutorials\npublished: true\n")) [4..132]
          Heading { level: H1, id: None, classes: [], attrs: [] } [137..155]
            Text(Borrowed("Getting Started")) [139..154]
          Paragraph [156..210]
            Text(Borrowed("This is a comprehensive guide to getting with started")) [156..209]
          Heading { level: H2, id: None, classes: [], attrs: [] } [211..227]
            Text(Borrowed("Installation")) [214..226]
          Paragraph [228..243]
            Text(Borrowed("First, install")) [228..242]
        "#);

        let (fm_opt, _, _) = scan_note(&path);

        let fm = fm_opt.unwrap();

        assert_debug_snapshot!(fm, @r#"
        Mapping {
            "title": String("Getting Started"),
            "author": String("Jane Doe"),
            "date": String("2024-03-15"),
            "tags": Sequence [
                String("programming"),
                String("tutorial"),
            ],
            "category": String("tutorials"),
            "published": Bool(true),
        }
        "#);
    }
}
