id = "oyster"
name = "Oyster"
version = "0.0.1"
schema_version = 1
authors = ["Hongyu Lin"]
description = "Oystermark LSP support for Markdown"

[language_servers.oystermark-lsp]
name = "oyster"
languages = ["Markdown"]
