name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  fmt:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: "5.4"
          dune-cache: true
          opam-pin: false
      - run: opam pin add -yn opentelemetry git+https://github.com/ocaml-tracing/ocaml-opentelemetry.git
      - run: opam pin add -yn opentelemetry-client git+https://github.com/ocaml-tracing/ocaml-opentelemetry.git
      - run: opam pin add -yn opentelemetry-client-cohttp-eio git+https://github.com/ocaml-tracing/ocaml-opentelemetry.git
      - run: opam install . --deps-only
      - run: opam install ocamlformat
      - run: opam exec -- dune fmt
      - run: git diff --exit-code

  doc:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: "5.4"
          dune-cache: true
          opam-pin: false
      - run: opam pin add -yn opentelemetry git+https://github.com/ocaml-tracing/ocaml-opentelemetry.git
      - run: opam pin add -yn opentelemetry-client git+https://github.com/ocaml-tracing/ocaml-opentelemetry.git
      - run: opam pin add -yn opentelemetry-client-cohttp-eio git+https://github.com/ocaml-tracing/ocaml-opentelemetry.git
      - run: opam install . --deps-only --with-doc --with-test
      - run: opam exec -- dune build @doc-private
